H071231064
IhlasulMufti/LAB-AP-01-2023 pull request #10
Opened 2023-09-30 02:02 UTC by Yousran

2023-09-30 02:44 UTC, IhlasulMufti requested changes

2023-09-30 02:44 UTC, IhlasulMufti commented on H071231064/Praktikum-3/TP3_1_H071231064.py
> +    a,b = b, a + b
perbaiki ini

2023-09-30 03:43 UTC, IhlasulMufti approved these changes

2023-10-07 13:54 UTC, IhlasulMufti requested changes

2023-10-07 13:54 UTC, IhlasulMufti commented on H071231064/Praktikum-4/TP4_4_H071231064.py
> +    # elif(mosC <= catA & catB):
hapusmi kode yang tidak terpakai

2023-10-07 13:54 UTC, IhlasulMufti commented on H071231064/Praktikum-4/TP4_5_H071231064.py
> +        return
dan ini fungsi returnya untuk apa? Apa yang dia return?

2023-10-09 00:51 UTC, Yousran commented on H071231064/Praktikum-4/TP4_5_H071231064.py
> +        return
return jika nilai suku nya negatif atau angka 0. di versi updated nya sudah ku ubah menjadi return print()

2023-10-09 02:20 UTC, IhlasulMufti approved these changes

2023-10-13 09:52 UTC, merged